augmenter_model: v0.3
bbox_thr: 0.8
camerasToUse:
- Cam0
- Cam1
- Cam2
filterFrequency: 4.0
imageUpsampleFactor: 4
openSimModel: LaiUhlrich2022_NHE
poseDetector: mmpose
scalingSetup: any_pose
verticalOffset: -0.2419061483192444
